import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import api from '../lib/api'
import StatusBanner from './StatusBanner'

export default function ReportExportBar({ reportType, filters = {} }) {
  const { t } = useTranslation()
  const [loadingFormat, setLoadingFormat] = useState(null) // 'pdf' | 'docx' | 'xlsx' | null
  const [error, setError] = useState('')

  const isOperational = reportType === 'operational'
  const title = isOperational
    ? t('exportBar_opTitle', 'Exportar Reporte Operativo')
    : t('exportBar_mgTitle', 'Exportar Reporte de Gestión Agroecológica')

  const subtitle = isOperational
    ? t(
        'exportBar_opSub',
        'Descarga el informe completo de actividad con indicadores clave, gráficos de tendencia embebidos y tablas de usuarios y regiones.'
      )
    : t(
        'exportBar_mgSub',
        'Descarga el informe agregado con KPIs agroecológicos, gráficas de evolución multiobjetivo embebidas y el ranking del Frente de Pareto.'
      )

  const handleExport = async (format) => {
    setLoadingFormat(format)
    setError('')
    try {
      const params = new URLSearchParams()
      if (filters.fecha_inicio) params.append('fecha_inicio', filters.fecha_inicio)
      if (filters.fecha_fin) params.append('fecha_fin', filters.fecha_fin)
      if (filters.region) params.append('region', filters.region)
      if (filters.usuario_id) params.append('usuario_id', filters.usuario_id)
      if (filters.periodo) params.append('periodo', filters.periodo)
      if (filters.top_n) params.append('top_n', String(filters.top_n))

      // 1. Fetch export data with charts generated by backend
      const endpoint = isOperational
        ? `/api/admin/reports/operational/export?${params.toString()}`
        : `/api/admin/reports/management/export?${params.toString()}`

      const response = await api.get(endpoint)
      const exportPayload = response.data.data
      const charts = response.data.charts || {}

      // 2. Load dedicated exporter library
      const exporters = await import('../lib/generalReportExporters')

      if (isOperational) {
        if (format === 'pdf') {
          exporters.exportOperationalReportToPdf(exportPayload, filters, charts)
        } else if (format === 'docx') {
          await exporters.exportOperationalReportToDocx(exportPayload, filters, charts)
        } else if (format === 'xlsx') {
          exporters.exportOperationalReportToExcel(exportPayload, filters)
        }
      } else {
        if (format === 'pdf') {
          exporters.exportManagementReportToPdf(exportPayload, filters, charts)
        } else if (format === 'docx') {
          await exporters.exportManagementReportToDocx(exportPayload, filters, charts)
        } else if (format === 'xlsx') {
          exporters.exportManagementReportToExcel(exportPayload, filters)
        }
      }
    } catch (err) {
      console.error('Error durante la exportación:', err)
      setError(
        err.response?.data?.detail ||
          t('exportBar_error', 'No fue posible generar el archivo de exportación. Intente nuevamente.')
      )
    } finally {
      setLoadingFormat(null)
    }
  }

  return (
    <div className="rounded-2xl border border-slate-200/90 bg-white p-4.5 sm:p-6 shadow-xs transition dark:border-slate-800 dark:bg-slate-900">
      {error ? (
        <div className="mb-4">
          <StatusBanner tone="error">{error}</StatusBanner>
        </div>
      ) : null}

      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="15"
                height="15"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
            </span>
            <h3 className="font-bold text-slate-900 dark:text-slate-100 font-display text-sm sm:text-base">
              {title}
            </h3>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 max-w-xl">
            {subtitle}
          </p>
        </div>

        {/* Action Buttons matching AdminSimulationsPage style */}
        <div className="flex flex-wrap items-center gap-2 shrink-0">
          {/* PDF Button */}
          <button
            type="button"
            onClick={() => handleExport('pdf')}
            disabled={loadingFormat !== null}
            className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 shadow-xs transition hover:bg-slate-50 disabled:opacity-50 dark:border-slate-800 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
            title="Exportar a PDF con gráficos embebidos"
          >
            {loadingFormat === 'pdf' ? (
              <svg className="animate-spin h-3.5 w-3.5 text-rose-500" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
            ) : (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="text-rose-500"
              >
                <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
                <polyline points="14 2 14 8 20 8" />
              </svg>
            )}
            <span>{loadingFormat === 'pdf' ? t('exportBar_generating', 'Generando...') : 'Exportar PDF'}</span>
          </button>

          {/* Word Button */}
          <button
            type="button"
            onClick={() => handleExport('docx')}
            disabled={loadingFormat !== null}
            className="inline-flex items-center gap-1.5 rounded-xl bg-blue-600 px-3.5 py-2 text-xs font-semibold text-white shadow-xs transition hover:bg-blue-500 disabled:opacity-50"
            title="Exportar a Microsoft Word (.docx) con gráficos embebidos"
          >
            {loadingFormat === 'docx' ? (
              <svg className="animate-spin h-3.5 w-3.5 text-white" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
            ) : (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
                <polyline points="14 2 14 8 20 8" />
              </svg>
            )}
            <span>{loadingFormat === 'docx' ? t('exportBar_generating', 'Generando...') : 'Exportar Word'}</span>
          </button>

          {/* Excel Button */}
          <button
            type="button"
            onClick={() => handleExport('xlsx')}
            disabled={loadingFormat !== null}
            className="inline-flex items-center gap-1.5 rounded-xl bg-green-600 px-3.5 py-2 text-xs font-semibold text-white shadow-xs transition hover:bg-green-500 disabled:opacity-50"
            title="Exportar a Microsoft Excel (.xlsx) con tablas y KPIs"
          >
            {loadingFormat === 'xlsx' ? (
              <svg className="animate-spin h-3.5 w-3.5 text-white" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
            ) : (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                <line x1="3" y1="9" x2="21" y2="9" />
                <line x1="9" y1="21" x2="9" y2="9" />
              </svg>
            )}
            <span>{loadingFormat === 'xlsx' ? t('exportBar_generating', 'Generando...') : 'Exportar Excel'}</span>
          </button>
        </div>
      </div>
    </div>
  )
}
